name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: actions-html-validation@0.7.0
        with:
          files: "*.html"
          fail_on_error: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Lighthouse
        run: npm install -g lighthouse @lhci/cli

      - name: Run Performance Audits
        run: |
          lhci autorun --static-dist-dir=. \
          --collect.settings.chromeFlags="--no-sandbox" \
          --assert.preset=lighthouse:recommended \
          --upload.target=temporary-public-storage

      - name: Security Scan
        uses: shiftleft/scan-action@v2
        with:
          output: reports/
          type: 'code,dependencies'
          fail_on: medium

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Browser Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npx serve -p 3000
          wait-on: 'http://localhost:3000'

      - name: Accessibility Tests
        uses: pa11y/pa11y-ci@v3
        with:
          urls: "http://localhost:3000"
          standard: WCAG2AA
